base:
  image: koudaiii/ml-handson
  ports:
    - "8888:8888"
  command: /root/start.sh
server:
  image: koudaiii/ml-handson
  ports:
    - "3000:3000"
    - "8888:8888"
  command: /root/server.sh
developbase:
  build: .
  ports:
    - "8888:8888"
  command: /root/start.sh
developserver:
  build: .
  ports:
    - "3000:3000"
    - "8888:8888"
  command: /root/server.sh
